print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/catherine1/Documents/ColorsGame/Colors/Assets/3DModels/paintToken.mb"`)
{		
	file -o "/Users/catherine1/Documents/ColorsGame/Colors/Assets/3DModels/paintToken.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/catherine1/Documents/ColorsGame/Colors/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/catherine1/Documents/ColorsGame/Colors/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/catherine1/Documents/ColorsGame/Colors/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
